a,b,c,d,#
0,1
@
-
0,1,a,ta,va,xa,b,tb,vb,xb,c,tc,vc,xc,d,td,vd,xd,x0,F
0
F
0,@,,1,@,D,,,1,#,,x0,-,D,,,1,a,,a,1,D,,,1,b,,b,1,D,,,1,c,,c,1,D,,,1,d,,d,1,D,,,a,#,,ta,#,D,,,a,a,,a,a,D,,,a,b,,a,b,D,,,a,c,,a,c,D,,,a,d,,a,d,D,,,b,#,,tb,#,D,,,b,a,,b,a,D,,,b,b,,b,b,D,,,b,c,,b,c,D,,,b,d,,b,d,D,,,c,#,,tc,#,D,,,c,a,,c,a,D,,,c,b,,c,b,D,,,c,c,,c,c,D,,,c,d,,c,d,D,,,d,#,,td,#,D,,,d,a,,d,a,D,,,d,b,,d,b,D,,,d,c,,d,c,D,,,d,d,,d,d,D,,,ta,0,,ta,0,D,,,ta,a,,va,0,E,,,ta,b,,xa,0,E,,,ta,c,,xa,0,E,,,ta,d,,xa,0,E,,,tb,0,,tb,0,D,,,tb,a,,xb,0,E,,,tb,b,,vb,0,E,,,tb,c,,xb,0,E,,,tb,d,,xb,0,E,,,tc,0,,tc,0,D,,,tc,a,,xc,0,E,,,tc,b,,xc,0,E,,,tc,c,,vc,0,E,,,tc,d,,xc,0,E,,,td,0,,td,0,D,,,td,a,,xd,0,E,,,td,b,,xd,0,E,,,td,c,,xd,0,E,,,td,d,,vd,0,E,,,va,#,,va,#,E,,,va,0,,va,0,E,,,va,1,,1,1,D,,,va,a,,va,a,E,,,va,b,,va,b,E,,,va,c,,va,c,E,,,va,d,,va,d,E,,,vb,#,,vb,#,E,,,vb,0,,vb,0,E,,,vb,1,,1,1,D,,,vb,a,,vb,a,E,,,vb,b,,vb,b,E,,,vb,c,,vb,c,E,,,vb,d,,vb,d,E,,,vc,#,,vc,#,E,,,vc,0,,vc,0,E,,,vc,1,,1,1,D,,,vc,a,,vc,a,E,,,vc,b,,vc,b,E,,,vc,c,,vc,c,E,,,vc,d,,vc,d,E,,,vd,#,,vd,#,E,,,vd,0,,vd,0,E,,,vd,1,,1,1,D,,,vd,a,,vd,a,E,,,vd,b,,vd,b,E,,,vd,c,,vd,c,E,,,vd,d,,vd,d,E,,,x0,-,,F,-,D,,,x0,0,,x0,-,D,,,xa,#,,xa,#,E,,,xa,0,,xa,0,E,,,xa,1,,1,-,D,,,xa,a,,xa,a,E,,,xa,b,,xa,b,E,,,xa,c,,xa,c,E,,,xa,d,,xa,d,E,,,xb,#,,xb,#,E,,,xb,0,,xb,0,E,,,xb,1,,1,-,D,,,xb,a,,xb,a,E,,,xb,b,,xb,b,E,,,xb,c,,xb,c,E,,,xb,d,,xb,d,E,,,xc,#,,xc,#,E,,,xc,0,,xc,0,E,,,xc,1,,1,-,D,,,xc,a,,xc,a,E,,,xc,b,,xc,b,E,,,xc,c,,xc,c,E,,,xc,d,,xc,d,E,,,xd,#,,xd,#,E,,,xd,0,,xd,0,E,,,xd,1,,1,-,D,,,xd,a,,xd,a,E,,,xd,b,,xd,b,E,,,xd,c,,xd,c,E,,,xd,d,,xd,d,E,,,
Explicação: o primeiro estado é o 1. ele lê a primeira letra, coloca 1 no lugar e vai para o estado a, b, c ou d. esse estado vai para a direita até achar o #. quando achar o #, vai para o estado ta (caso tenha lido a), que vai indo para a direita até não ser um 0. caso o primeiro caractere depois de 0 for a, vai para o estado va, se não, para o xa (análogamente para as outras letras). se for va, escreve 0 no lugar e volta para a esquerda até achar o 1, e volta para o estado 1. se for xa, faz o mesmo, mas troca o 1 por vazio. segue esse processo até ler um # no estado 1. quando isso acontecer, escreve vazio no lugar e vai para a direita apagando toda a sequência de 0.
